version: '3'
services:
  backend:
  # diretorio onde o docker file se encontra
    build: .
    container_name: store_manager
    ports:
      - 3001:3001
      - 9229:9229
    command: run dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - store_manager_net

  db:
    image: mysql:8.0.32
    container_name: store_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: StoreManager
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      store_manager_net:
        aliases:
          - sm_remote_db

networks:
  store_manager_net:
    name: store_manager_net
